create table if not exists stg.consulta_cand_2026_df (
    dt_geracao text,
    hh_geracao text,
    ano_eleicao text,
    cd_tipo_eleicao text,
    nm_tipo_eleicao text,
    nr_turno text,
    cd_eleicao text,
    ds_eleicao text,
    dt_eleicao text,
    tp_abrangencia text,
    sg_uf text,
    sg_ue text,
    nm_ue text,
    cd_cargo text,
    ds_cargo text,
    sq_candidato text,
    nr_candidato text,
    nm_candidato text,
    nm_urna_candidato text,
    nm_social_candidato text,
    nr_cpf_candidato text,
    ds_email text,
    cd_situacao_candidatura text,
    ds_situacao_candidatura text,
    tp_agremiacao text,
    nr_partido text,
    sg_partido text,
    nm_partido text,
    nr_federacao text,
    nm_federacao text,
    sg_federacao text,
    ds_composicao_federacao text,
    sq_coligacao text,
    nm_coligacao text,
    ds_composicao_coligacao text,
    sg_uf_nascimento text,
    dt_nascimento text,
    nr_titulo_eleitoral_candidato text,
    cd_genero text,
    ds_genero text,
    cd_grau_instrucao text,
    ds_grau_instrucao text,
    cd_estado_civil text,
    ds_estado_civil text,
    cd_cor_raca text,
    ds_cor_raca text,
    cd_ocupacao text,
    ds_ocupacao text,
    cd_sit_tot_turno text,
    ds_sit_tot_turno text,
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);

create table if not exists stg.consulta_cand_complementar_2026_df (
    dt_geracao text,
    hh_geracao text,
    ano_eleicao text,
    cd_eleicao text,
    sq_candidato text,
    cd_detalhe_situacao_cand text,
    ds_detalhe_situacao_cand text,
    cd_nacionalidade text,
    ds_nacionalidade text,
    cd_municipio_nascimento text,
    nm_municipio_nascimento text,
    nr_idade_data_posse text,
    st_quilombola text,
    cd_etnia_indigena text,
    ds_etnia_indigena text,
    vr_despesa_max_campanha text,
    st_reeleicao text,
    st_declarar_bens text,
    nr_protocolo_candidatura text,
    nr_processo text,
    cd_situacao_candidato_pleito text,
    ds_situacao_candidato_pleito text,
    cd_situacao_candidato_urna text,
    ds_situacao_candidato_urna text,
    st_candidato_inserido_urna text,
    nm_tipo_destinacao_votos text,
    cd_situacao_candidato_tot text,
    ds_situacao_candidato_tot text,
    st_prest_contas text,
    st_substituido text,
    sq_substituido text,
    sq_ordem_suplencia text,
    dt_aceite_candidatura text,
    cd_situacao_julgamento text,
    ds_situacao_julgamento text,
    cd_situacao_julgamento_pleito text,
    ds_situacao_julgamento_pleito text,
    cd_situacao_julgamento_urna text,
    ds_situacao_julgamento_urna text,
    cd_situacao_cassacao text,
    ds_situacao_cassacao text,
    cd_situacao_cassacao_midia text,
    ds_situacao_cassacao_midia text,
    cd_situacao_diploma text,
    ds_situacao_diploma text,
    cd_genero_fefc text,
    ds_genero_fefc text,
    cd_cor_raca_fefc text,
    ds_cor_raca_fefc text,
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);

create table if not exists stg.eleitorado_local_votacao_2026_df (
    dt_geracao text,
    hh_geracao text,
    aa_eleicao text,
    dt_eleicao text,
    ds_eleicao text,
    nr_turno text,
    sg_uf text,
    cd_municipio text,
    nm_municipio text,
    nr_zona text,
    nr_secao text,
    cd_tipo_secao_agregada text,
    ds_tipo_secao_agregada text,
    nr_secao_principal text,
    nr_local_votacao text,
    nm_local_votacao text,
    cd_tipo_local text,
    ds_tipo_local text,
    ds_endereco text,
    nm_bairro text,
    nr_cep text,
    nr_telefone_local text,
    nr_latitude text,
    nr_longitude text,
    cd_situ_local_votacao text,
    ds_situ_local_votacao text,
    cd_situ_zona text,
    ds_situ_zona text,
    cd_situ_secao text,
    ds_situ_secao text,
    cd_situ_localidade text,
    ds_situ_localidade text,
    cd_situ_secao_acessibilidade text,
    ds_situ_secao_acessibilidade text,
    qt_eleitor_secao text,
    qt_eleitor_eleicao_federal text,
    qt_eleitor_eleicao_estadual text,
    qt_eleitor_eleicao_municipal text,
    nr_local_votacao_original text,
    nm_local_votacao_original text,
    ds_endereco_locvt_original text,
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);

create table if not exists stg.tre_locais_2026_df (
    uf text,
    ze text,
    nom_local text,
    num_local text,
    bairro_local text,
    endereco_local text,
    num_latitude_local text,
    num_longitude_local text,
    qtde_secoes text,
    qtde_eleitores_aptos text,
    qtde_eleitores_nao_aptos text,
    is_total boolean not null default false,
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);

create table if not exists stg.tre_locais_secao_2026_df (
    ze text,
    bairro_local text,
    nom_local text,
    num_local text,
    qtde_eleitores_aptos text,
    maximo_secao text,
    minimo_secao text,
    secoes_com_menos_de_200 text,
    secoes_com_mais_de_360 text,
    agregar_menos_50 text,
    secoes_com_mais_de_400 text,
    is_total boolean not null default false,
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);

create table if not exists stg.tre_locais_secao_agrupadas_2026_df (
    uf text,
    ze text,
    bairro_local text,
    num_local text,
    nom_local text,
    secoes_numero text,
    qtde_secoes text,
    qtde_aptos text,
    is_total boolean not null default false,
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);

create table if not exists stg.tre_secoes_2026_df (
    ze text,
    num_local text,
    bairro_local text,
    nom_local text,
    num_secao text,
    aptos text,
    suspensos text,
    is_total boolean not null default false,
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);

create table if not exists stg.geo_ra_centroid_atualizado (
    ra_nome text,
    ra_codigo text,
    ra_areakm2 text,
    longitude text,
    latitude text,
    geometry_type text,
    geometry_json text,
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);

create table if not exists stg.ra_shapefile (
    ra_cira text,
    ra_codigo text,
    ra_nome text,
    ra_path text,
    ra_areakm2 text,
    st_area_sh text,
    st_length text,
    geometry_type text,
    geometry_json text,
    geom geometry(Geometry, 31983),
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);
