create table if not exists stg.perfil_eleitor_secao_2026_df (
    dt_geracao text,
    hh_geracao text,
    aa_eleicao text,
    sg_uf text,
    cd_municipio text,
    nm_municipio text,
    nr_zona text,
    nr_secao text,
    nr_local_votacao text,
    nm_local_votacao text,
    cd_genero text,
    ds_genero text,
    cd_estado_civil text,
    ds_estado_civil text,
    cd_faixa_etaria text,
    ds_faixa_etaria text,
    cd_grau_escolaridade text,
    ds_grau_escolaridade text,
    cd_raca_cor text,
    ds_raca_cor text,
    cd_identidade_genero text,
    ds_identidade_genero text,
    cd_quilombola text,
    ds_quilombola text,
    cd_interprete_libras text,
    ds_interprete_libras text,
    qt_eleitores text,
    qt_eleitores_biometria text,
    qt_eleitores_deficiencia text,
    qt_eleitores_nome_social text,
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);

create table if not exists stg.perfil_eleitor_secao_2026_go (
    dt_geracao text,
    hh_geracao text,
    aa_eleicao text,
    sg_uf text,
    cd_municipio text,
    nm_municipio text,
    nr_zona text,
    nr_secao text,
    nr_local_votacao text,
    nm_local_votacao text,
    cd_genero text,
    ds_genero text,
    cd_estado_civil text,
    ds_estado_civil text,
    cd_faixa_etaria text,
    ds_faixa_etaria text,
    cd_grau_escolaridade text,
    ds_grau_escolaridade text,
    cd_raca_cor text,
    ds_raca_cor text,
    cd_identidade_genero text,
    ds_identidade_genero text,
    cd_quilombola text,
    ds_quilombola text,
    cd_interprete_libras text,
    ds_interprete_libras text,
    qt_eleitores text,
    qt_eleitores_biometria text,
    qt_eleitores_deficiencia text,
    qt_eleitores_nome_social text,
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);

create table if not exists stg.votacao_secao_2022_df (
    dt_geracao text,
    hh_geracao text,
    ano_eleicao text,
    cd_tipo_eleicao text,
    nm_tipo_eleicao text,
    nr_turno text,
    cd_eleicao text,
    ds_eleicao text,
    dt_eleicao text,
    tp_abrangencia text,
    sg_uf text,
    sg_ue text,
    nm_ue text,
    cd_municipio text,
    nm_municipio text,
    nr_zona text,
    nr_secao text,
    cd_cargo text,
    ds_cargo text,
    nr_votavel text,
    nm_votavel text,
    qt_votos text,
    nr_local_votacao text,
    sq_candidato text,
    nm_local_votacao text,
    ds_local_votacao_endereco text,
    source_file text not null,
    loaded_at timestamptz not null default now(),
    row_number integer not null
);
